cursor_text_color #e5e1e9
cursor #c9c3dc

foreground            #e5e1e9
background            #141318
selection_foreground  #312e41
selection_background  #c9c3dc
scrollbar_handle_color #c9bfff
url_color             #c9bfff

#tab
active_tab_foreground   #48454e
active_tab_background   #c9bfff
inactive_tab_foreground #48454e
inactive_tab_background #938f99
tab_bar_background      #141318
