foreground #e2e2e8
background #111318
cursor #acc7ff
selection_background #acc7ff
selection_foreground #002e68

color0 #0c0e13
color8 #8d909c
color1 #acc7ff
color9 #acc7ff
color2 #b8c6e8
color10 #b8c6e8
color3 #f6aef9
color11 #f6aef9
color4 #7ca3ef
color12 #7ca3ef
color5 #3b4965
color13 #3b4965
color6 #d08bd4
color14 #d08bd4
color7 #c3c6d2
color15 #e2e2e8
