hl.config({ animations = { enabled = true } })

hl.curve("wind",         { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("winIn",        { type = "bezier", points = { {0.1, 1.1},  {0.1, 1.1}  } })
hl.curve("winOut",       { type = "bezier", points = { {0.3, -0.3}, {0, 1}      } })
hl.curve("liner",        { type = "bezier", points = { {1, 1},      {1, 1}      } })
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5},  {0.75, 1.0} } })

hl.animation({ leaf = "windows",     enabled = true, speed = 6,    bezier = "wind",   style = "slide" })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 6,    bezier = "winIn",  style = "slide" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 5,    bezier = "winOut", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5,    bezier = "wind",   style = "slide" })
hl.animation({ leaf = "border",      enabled = true, speed = 1,    bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30,   bezier = "liner",  style = "loop" })
hl.animation({ leaf = "layers",      enabled = true, speed = 6,    bezier = "wind",   style = "popin 90%" })
hl.animation({ leaf = "layersIn",    enabled = true, speed = 6,    bezier = "winIn",  style = "popin 90%" })
hl.animation({ leaf = "layersOut",   enabled = true, speed = 5,    bezier = "winOut", style = "popin 90%" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 5,    bezier = "wind",   style = "slide" })
hl.animation({ leaf = "fadeIn",      enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",     enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",        enabled = true, speed = 3.03, bezier = "almostLinear" })

hl.config({ dwindle = { preserve_split = true } })
